apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: grupoa4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: python
        # CORREGIDO: Nombre coincidente con el Jenkinsfile
        image: grupo4a/pythona4:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # RECOMENDADO: Añadir límites para evitar caídas por falta de RAM
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: DB_HOST
          value: "mariadba4"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: pythona4 
  namespace: grupoa4
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8080      # Puerto externo (VIP)
      targetPort: 5000 # Puerto interno de la App (Flask/FastAPI)
