apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: grupoa4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: apache
        # CORREGIDO: Nombre coincidente con REGISTRY_WAF del Jenkinsfile
        image: grupo4a/apachea4:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # RECOMENDADO: Recursos para evitar que el pod se caiga por falta de RAM
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: grupoa4
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30604  # Puerto de entrada para Cypress y ZAP
