apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: grupoa4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      # --- AQUÍ EMPIEZAN LAS ANOTACIONES DE ELASTICSEARCH ---
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.paths: /var/log/apache2/*.log         
        co.elastic.logs/module: apache
        co.elastic.logs/fileset.access.enabled: "true"
        co.elastic.logs/fileset.error.enabled: "true"
        co.elastic.logs/processors.add_fields.fields.service: apache-grupoa4
        co.elastic.logs/processors.add_fields.fields.env: grupoa4
      # --- FIN DE LAS ANOTACIONES ---
      labels:
        app: apache
        env: grupoa4  # Añadida la etiqueta de entorno
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: apache
        image: grupo4a/apachea4:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: grupoa4
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30604
